apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.244.0.43
  selector:
    app: crud-service
  externalIPs: 10.111.131.62
  ports:
    - targetPort: 46468
      port: 46468
