apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: ClusterIP
  selector:
    app: crud-service
  ports:
    - targetPort: 80
      port: 80
      selector:
        name: crud-service
        type: back-end-api