apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: ClusterIP
  clusterIP: 10.96.46.21
  selector:
    app: crud-service
  externalIPs:
    - 10.111.131.62
  ports:
    - targetPort: 46468
      port: 46468
