apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  type: ClusterIP
  selector:
    app: crud-service
    name: crud-service
    type: back-end-api
  ports:
    - targetPort: 80087
      port: 80087
