apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: crud-service
    spec:
      containers:
        - name: crud-service
          image: eribyteofficial/crud-service
          imagePullPolicy: Always
          ports:
            - containerPort: 46468
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: schema
              valueFrom:
                configMapKeyRef:
                  name: ${CONFIG_NAME}
                  key: schema
            - name: spring.datasource.driver-class-name
              valueFrom:
                configMapKeyRef:
                  name: ${CONFIG_NAME}
                  key: spring.datasource.driver-class-name
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: ${CONFIG_NAME}
                  key: spring.datasource.url
            - name: spring.jpa.database-platform
              valueFrom:
                configMapKeyRef:
                  name: ${CONFIG_NAME}
                  key: spring.jpa.database-platform
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: ${CONFIG_NAME}
                  key: spring.datasource.username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: spring.datasource.password
            - name: security.delete.code
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: security.delete.code
            - name: security.oauth.password
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: security.oauth.password

  selector:
    matchLabels:
      app: crud-service
